services:
  database:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password@1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: Password@1234
      MYSQL_DATABASE: eshopdb
  tomcat:
    image: tomcat:8.5.31-jre8
    ports:
      - "8080:81"
    links:
      - app
    volumes_from:
      - app
  app:
    image: ${DOCKER_REGISTRY-}eshop
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - wars:/opt/tomcat/webapps
    links:
      - database
volumes:
  wars:
    driver: local