services:
  database:
    image: mysql:latest
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: Password@1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: Password@1234
      MYSQL_DATABASE: eshopdb
  tomcat:
    image: tomcat:8.5.31-jre8
    ports:
      - 8080
    links:
      - app
    volumes_from:
      - app
  app:
    image: ${{build_image}}
    volumes:
      - wars:/opt/tomcat/webapps
    links:
      - database
volumes:
  wars:
    driver: local